### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by doctormo** [Sispheor/Piclodio2#15]
The documentation should start with a description of what the project is and what it does. I figured it out from bits of information further on but it should be right at the top.

I also noticed the docs use wget instead or pip, is the raspberry pi restricted from using pip to install python packages? `pip install Django==1.6` seems easier.

Also many of these instructions might be good to fold into an init or setup script for convenience. But that's a nice to have :-)

**Comment by Sispheor** [comment]
We should ddd Nginx to the possibility of kind of installation

**Comment by Sispheor** [comment]
Doc ok now.
