### ISSUE TITLE
Add MP3/OGG Support 

### ISSUE THREAD

**Issue by Anthael** [Sispheor/Piclodio2#21]
Hi

Maybe possible to play a local mp3,ogg sound instead of a radio ?
I could only select a webradio

Thanks by advance

**Comment by arnaudmm** [comment]
I think the idea is not to provide a local library player..

If we want to do this, this will be a lot of work and basically developing a winamp/spotify like

Don't you think?

**Comment by Sispheor** [comment]
Agreed. It is not the objective of Piclodio to provide this kind of feature so far.
